--- # Leverage efficiency config file

# This file allows control over the data processing pipeline without any need
# to edit the code.

# This section specifies the folder structure
source data folder: './data/1-source/'
source data filenames: 'source_data_file_names.yaml'
intermediate data folder: './data/2-intermediate/'
updated data folder: './data/3-update/'
data_folder: './data/4-load/'
analysis_folder: './data/5-analysis/'
plots_folder: './data/6-figures/'

# This section specifies which data sets to process in the extract, transform and update
# pipeline stages
data processing stages:
  run: True
  assets:
    - BTC
    - MAD
    - SP500
  daily interest rates:
    - FED
  monthly interest rates:
    - FEDM

# This section provides control over the various steps in the analysis pipeline
# stage, including which pairs to analyse and which steps of the analysis to run
# and what parameters to pass into the analysis.
analysis:
  run: False
  pairs:
    - BTC-FED
    - SP500-FED
    - MAD-FEDM

  analysis stages:
     calculate grids: True
     fit parameters: True
     expanding window calculations: True
     l_opt variance calculations: True
     fixed window calculations: True

# This section provides control over the plots pipeline stage, including which
# pairs to plots and which figures to generate for each pair.
plots:
  run: False
  pairs:
    - BTC-FED
    - SP500-FED
  figures:
    expanding windows significance: True
    equity trajectories: True
    final equity vs leverage: True
    growth rate vs leverage: True
    l_opt variance: True
    expanding windows: True
    fixed windows: True
    compare assets: False

# Turning this one will run the paper_plots.py stage which generates the
# plots used in the manuscript. This assumes that the relevant data analysis
# has been performed by the previous stages.
paper plots:
  run: False

# Turning this one will run the lecture_plots.py stage which generates the
# plots used in the EE lecture notes. This again assumes that all relevant data
# analyses have been performed by the previous stages.
lecture plots:
  run: False
