--- # Leverage efficiency config file

# This file allows control over the data processing pipeline without any need
# to edit the code.

# This section specifies the folder structure
source data folder: './data/1-source/'
intermediate data folder: './data/2-intermediate/'
updated data folder: './data/3-update/'
data_folder: './data/4-load/'
analysis_folder: './data/5-analysis/'
plots_folder: './data/6-figures/lecture_notes/'

# This section specifies which data sets to process in the extract, transform and update
# pipeline stages
data processing stages:
  run: False
  assets:
    - MAD
    - BRK
  daily interest rates:
    - FED
  monthly interest rates:
    - FEDM

# This section provides control over the various steps in the analysis pipeline
# stage, including which pairs to analyse and which steps of the analysis to run
# and what parameters to pass into the analysis.
analysis:
  run: False
  pairs:
    - BTC-FED
  analysis stages:
     calculate grids: True
     fit parameters: False
     expanding window calculations: False
     l_opt variance calculations: False
     fixed window calculations: False

# This section provides control over the plots pipeline stage, including which
# pairs to plots and which figures to generate for each pair.
plots:
  run: False
  pairs:
    - BTC-FED
  figures:
    equity trajectories: False
    final equity vs leverage: False
    growth rate vs leverage: False
    l_opt variance: False
    expanding windows: False
    fixed windows: True
    compare assets: False

# Turning this one will run the paper_plots.py stage which generates the
# plots used in the manuscript. This assumes that the relevant data analysis
# has been performed by the previous stages.
paper plots:
  run: False

# Turning this one will run the lecture_plots.py stage which generates the
# plots used in the EE lecture notes. This again assumes that all relevant data
# analyses have been performed by the previous stages.
lecture plots:
  run: True
