name: env-leverage_efficiency
channels:
- conda-forge
dependencies:
- ca-certificates=2023.5.7
- certifi=2023.5.7
- ipykernel=6.24.0
- lmfit=1.2.1
- matplotlib=3.7.2
- numpy=1.25.0
- openpyxl=3.1.2
- openssl=3.1.1
- pandas=2.0.3
- python=3.11.4
- pyyaml=6.0
- requests=2.31.0
- scipy=1.11.1
- yfinance=0.2.22
